#!/bin/bash
# This script installs Puppet on the client OS, then runs Puppet.  All configuration should be done in Puppet, so all this should do is get the OS to the point that a Puppet run can complete successfully

set -u
set -e

# OS-specific installs
RedHat() {
  if [ ! -f '/etc/yum.repos.d/puppet.repo' ]
  then
    echo "Adding Puppet repositories"
    echo -e "[puppet-products]\nname=puppet-products\nbaseurl=http://yum.puppetlabs.com/el/\$releasever/products/\$basearch\ngpgcheck=1\nenabled=1" > /etc/yum.repos.d/puppet.repo
    echo -e "[puppet-dependencies]\nname=puppet-dependencies\nbaseurl=http://yum.puppetlabs.com/el/\$releasever/dependencies/\$basearch\ngpgcheck=1\nenabled=1" >> /etc/yum.repos.d/puppet.repo
  fi
set +e
  rpm -q puppet
  installed=$?
set -e
  if [ $installed -ne 0 ]
  then
    echo "Importing puppetlabs GPG key"
    rpm --import http://yum.puppetlabs.com/RPM-GPG-KEY-puppetlabs
    echo "Installing Puppet"
    yum -y install puppet
  fi
}

Debian() {
  if [ ! -f '/etc/apt/sources.list.d/puppet.list' ]
  then
    echo "Adding Puppet repository"
    echo 'deb http://apt.puppetlabs.com trusty main' > /etc/apt/sources.list.d/puppet.list
  fi
set +e
  dpkg -l puppet
  installed=$?
set -e
  if [ $installed -ne 0 ]
  then
    echo "Importing puppetlabs GPG key"
    apt-key add /vagrant/provision/puppet/pubkey.gpg
    echo "Installing Puppet"
    apt-get update
    apt-get -y install puppet
  fi
}

if [ -f '/etc/debian_version' ]
then
  osfamily='Debian'
  Debian
elif [ -f '/etc/redhat-release' ]
then
  osfamily='RedHat'
  RedHat
else
  osfamily='unsupported'
  echo "Unsupported OS."
  exit 1
fi

# Run Puppet
puppet apply /vagrant/provision/puppet/manifests/site.pp --modulepath=/vagrant/provision/puppet/modules
